---
title: "Título maneiro"
author: |
  | Erlene Avelino 
  | Louise Almeida da Silva
  | Pedro Luz de Castro
  | Renan Almeida
output: pdf_document
documentclass: article
bibliography: bibliografia.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1. Resumo

O movimento de incorporação das redes sociais no processo eleitoral e suas constantes inovações no Brasil e no mundo, suscitam grandes expectativas, algumas delas relacionadas a compreensões normativas de democratização.Poderíamos citar, desde especulações sobre a redução de desigualdades de acesso a recursos competitivos entre candidatos, até pressuposições sobre a adoção de uma comunicação mais responsiva e deliberativa, entre elites políticas e eleitores. Neste texto, contudo, nos inspiramos na compreensão desenvolvida em trabalhos empíricos no campo da comunicação e política [@BragaCarlomagno2018], que asseveram que, mais do que suposições e uma discussão sobre os potenciais das ferramentas digitais, é necessário observar os usos que os atores verdadeiramente fazem delas. Nesse sentido, buscaremos aqui promover essa perspectiva, discutindo brevemente algumas pesquisas sobre o contexto brasileiro e apresentando um tutorial com uma alternativa de como realizar pesquisas com bases textuais de redes sociais, utilizando modelagem de tópicos (Topic Modeling). No exercício aplicado, procuramos estimar, por meio de dados do twitter, como o período eleitoral pode ter afetado os tópicos tratados pelos candidatos à presidência nas eleições de 2018.

## 2. Mídias digitais: campo político e ferramenta de pesquisa cada vez mais relevante

Talvez não restem dúvidas, passadas as eleições de 2018, de que as mídias sociais são um componente e fator político muito importante, e devem especialmente ser levados em conta para a compreensão das eleições no Brasil e do período eleitoral em si. Considerando que este campo, do uso político das ferramentas digitais, é intrinsecamente dinâmico, procuraremos nesta seção exemplificar algumas questões relevantes e discutir sobre a forma como as próprias mídias digitais foram e podem ser utilizadas pelos pesquisadores para aborda-las. Não temos a pretensão aqui de discutir todo o percurso de incorporação das mídias nas campanhas políticas, ou fazer uma revisão bibliográfica sobre o campo . A ideia é apenas tentar despertar o interesse e incentivar a pesquisa empírica. 
  
Comecemos falando do contexto. O que recorrentemente se ressalta sobre as mídias digitais e redes sociais é o seu caráter “desintermediado” [@Aggio2020]. Estamos, grosso modo, em uma nova era, distante dos antigos “filtros” dos meios de comunicação tradicionais e com possibilidades de interatividade imensas. A grande quantidade de usuários – eleitores – em conjunto, expostos continuamente a informações, vinculados por redes com disposições e ferramentas para interação, é obviamente um terreno fértil e igualmente estratégico para a política. Como resultado, as práticas tradicionais de campanha, baseadas nos meios antigos, foram solapados? O meio digital é agora o centro da disputa pelos votos? Utilizaremos os textos @MarquesSilvaMatos2011 e @AggioReis2013 para iniciar a discussão, e incorporaremos também as contribuições desenvolvidas por @BragaCarlomagno2018, @Aggio2020 e @MurtaMagalhaesPimentel2019.
  
A primeira questão é mais diretamente abordada por @MarquesSilvaMatos2011. Os autores procuram avaliar a estratégia de campanha de José Serra no twitter, explorando as mudanças na frequência e nos conteúdos das postagens, durante o período eleitoral de 2010. Como resultado, consideram que ainda que Serra seja um usuário assíduo e tenha tido, possivelmente, mais razões para utilizar a ferramenta de maneira a se mostrar mais acessível, sua campanha e métodos de abordagens dos eleitores foram basicamente tradicionais. Ou seja, possuía os mesmos princípios de divulgação e persuasão “de cima para baixo”, e não buscava uma relação dialógica, especialmente sobre propostas políticas, com os seus seguidores. @AggioReis2013 adotam uma estratégia de pesquisa semelhante, mas se aproximam mais da segunda questão que apontamos, sobre a centralidade do contexto das ferramentas digitais, neste caso, o facebook, para as campanhas vencedoras de 3 candidatos a prefeito de capitais brasileiras no ano de 2012.
  
Os autores (*ibid.*), nesse sentido, procuram relacionar o efeito da interação entre os candidatos e os usuários, com o sucesso eleitoral. Mais especificamente, eles observam um aumento quantitativo de interações às postagens dos candidatos e se atentam ao uso que os mesmos fizeram das “gramáticas preexistentes” da rede, como o compartilhamento de memes, fotos e vídeos. Com isso, poderíamos reformular a nossa pergunta da seguinte maneira: quem melhor incorpora as lógicas das ferramentas, tem maiores chances de vencer? Isso não parece muito plausível, ou ao menos não ainda. @BragaCarlomagno2018 realizam uma pesquisa de maior folego sobre a incorporação e influência das mídias digitais nas campanhas políticas no Brasil até 2016, com ênfase nas disputas pelos cargos majoritários. Os autores conseguem observar algumas tendências, contudo o grau de interação (curtidas, seguidores, compartilhamento, etc.) não é crescentemente e homogeneamente correlacionado, entre diferentes categorias de candidatos, com o sucesso eleitoral. Mas as eleições presidenciais apresentam resultados mais animadores, do que estaduais e municipais. 

O ponto principal, contudo, é que eles apontam que já em 2016 praticamente toda a classe política utiliza redes sociais. Nesse ponto, as desigualdades regionais não mais se verificam e podemos considerar que todo os candidatos teriam um patamar mínimo de acesso a esses meios e recurso de competição. Mas assim como, por obvio, existem muitas outras “fontes” de desigualdades nos processos de competição política, acumulam-se também casos de candidatos destacados nas redes sociais com um correspondente resultado eleitoral muito baixo (*ibid.*). Isso nos faz duvidar de que o meio digital é o centro de disputa pelos votos.
  
Mas você também deve estar pensando nas eleições de 2018. O então candidato Jair Bolsonaro, notoriamente não estava em vantagem nos meios de campanha tradicionais, como o Horário político eleitoral gratuito. @Aggio2020 procura avaliar se a campanha de Jair no twitter, lançou mão de mecanismos de interação direta com os usuários, dado que o próprio presidente enaltecia e enaltece as redes sociais, como uma maneira de comunicação desintermediada com “O povo”. É interessante destacar que a ideia mesmo de “interação” aqui, tem um sentido diferente do que foi abordado até então, nos textos de @AggioReis2013 e @BragaCarlomagno2018. Os dois últimos mediram nos referidos períodos eleitorais o que pode ser entendido como a audiência que os candidatos obtiveram, e não o diálogo, a interação, entre estes e os usuários. Marques (2011), por meio de análise de conteúdo das postagens, examina se a campanha de Serra se adaptou a lógica interativa da ferramenta, no mesmo sentido que @Aggio2020 veio a adotar posteriormente. 
  
A inovação do texto de @Aggio2020, foi interpretar e classificar as estratégias de comunicação eleitoral de Bolsonaro, adotando como o cerne de sua análise os diferentes graus de interação possibilitados pela própria ferramenta. Os mecanismos do twitter para a comunicação horizontal são as menções e os retuites, e o candidato pode se utilizar delas de maneira direta, substantivamente desenvolvendo um “bate papo” com os usuários acionados, ou indireta, utilizando como mera reiteração e/ou exemplificação do conteúdo compartilhado. Nesse sentido, pode-se compreender quais as formas de atividade foram majoritárias, mas também explorar suas associações a determinados atores, públicos e conteúdos estratégicos. Surpreendentemente, o uso dos recursos de interação e deliberação também não foram a prioridade desta campanha. 
  
A maioria das atividades de Bolsonaro foram de tuites originais, voltados para a propaganda e o ataque e exposição dos adversários políticos. A minoria de atividades interativas, estava associada a reverberação de mensagens de apoio, com extensivo uso de vídeos e artifícios imagéticos, e raríssima atenção a discussão de propostas políticas. Nesse sentido, observamos que as práticas tradicionais, mesmo neste caso atípico, não foram solapadas, apesar da simultânea e inegável centralidade adquirida pelas redes sociais. 
   
A pesquisa desenvolvida por @MurtaMagalhaesPimentel2019 apresentam uma outra dimensão desta centralidade, e traz para o Brasil estudos já mais comuns nos EUA, que procuram entender a correlação entre interações e sucesso eleitoral, como um novo formato de pesquisa com grande potencial de substituir as sondagens de voto. A noção é a de que a adesão as redes sociais é hoje no Brasil, tão generalizada e extensiva, que é possível construir indicadores confiáveis por meio dos dados digitais. 
   
Bom, de tudo isso retiramos que há uma óbvia convergência, de atração aos candidatos pelo imenso transito de pessoas que se expressam e interagem politicamente e visivelmente nas redes. Mas, alternativamente, não consideramos muito útil pressupor, ou derivar dos potenciais interativos e democráticos das redes, uma completa e automática transformação da política, como ilustramos no início do texto. Seria, como supor que a política se apropriará completamente desse meio, porque ele é “obviamente” melhor. Ou, que o meio invariavelmente irá impor uma adequação total aos políticos. Inspirados por estes trabalhos e através deles, pudemos entender que esse campo é intrinsecamente dinâmico e que há muitos ganhos quando nos aprofundamos na própria ferramenta através dos casos empíricos.
  
Através do estudo de @Aggio2020 sobre Bolsonaro, por exemplo, podemos ainda enxergar de maneira mais clara, que há na incorporação das lógicas das redes sociais por parte do candidatos, ao menos duas variantes. Uma, que o autor já havia explorado no estudo de 2013 com Reis, sobre o uso das linguagens “preexistentes” com a finalidade de mobilizar uma eventual militância; a outra, que pode simular um comportamento interativo e acessível do candidato, semelhante ao dos demais usuários. Este último pode estar vinculado a estratégias populistas, como no caso de Bolsonaro, ou a uma compreensão participacionista. Ainda não temos respostas, não sabemos exatamente como associar essa adequação ao sucesso, e as “curtidas” também não são um proxie certeiro. Há muito a ser explorado.
  
Uma perspectiva interessante, adotada por @MarquesSilvaMatos2011 e @AggioReis2013, é a de observar a mudança no comportamento dos candidatos, nos assuntos abordados e frequência de uso das mídias, em função do período eleitoral. Como ressaltamos anteriormente, os autores estavam tentando compreender as campanhas online e as estratégias utilizadas pelos candidatos. Na próxima seção, apresentaremos um tutorial com uma ideia semelhante, explorando os tuites dos principais candidatos à presidência da eleição de 2018. Explicaremos como fazer um gráfico de frequência e como explorar o conteúdo de tuites através da técnica de modelagem de tópicos (Topic Modeling), para em seguida, observar o efeito do período eleitoral sobre a frequência de uso e os principais assuntos utilizados por cada candidato. Nesse sentido, à diferença dos autores tratados aqui, não examinaremos as publicações dos candidatos através de análise de conteúdo.
  
É interessante observar que tanto @MarquesSilvaMatos2011 quanto @AggioReis2013, ressaltam o fato de que alguns candidatos de suas observações, haviam acabado de ingressar nas redes sociais ou tinham um perfil praticamente inativo antes do pleito. Talvez por isso, a diferença de frequência no uso das ferramentas tenha sido ainda mais importante para essas análises. Por sua vez, tanto os resultados de Serra [@MarquesSilvaMatos2011], quanto de Jair Bolsonaro [@Aggio2020] foram de campanhas que priorizaram estratégias “top down” e igualmente não discutiam sobre políticas substantivas. É possível supor que, passado o tempo, tenham havido maiores mudanças, e outras campanhas procurem discutir sobre propostas de políticas substantiva? Ou, é possível que campanhas procurem abordar não propostas, mas temas políticos, como uma ferramenta de mobilização adequada a essas redes? A nossa suposição, que não será desenvolvida aqui, é que talvez os comportamentos hoje, ou nas ultimas campanhas, não destoem tanto. Claro, em razão do maior peso das redes de maneira geral, ou de uma mudança provocada por ela, na distensão dos período de campanha. 

## 3. Tutorial: (pensar num título)

A proposta aqui é meramente ilustrativa e exploratória. O intuito é, nesse sentido, muito mais o de incentivar e instrumentalizar futuras análises. Vamos tentar observar quais os principais tópicos são tratados pelos candidatos Ciro Gomes, Fernando Haddad, Geraldo Alckmin, Guilherme Boulos, Jair Bolsonaro, Luiz Inácio Lula da Silva e Marina Silva, e, em seguida, analisar as mudanças destes tópicos e da frequência de postagens no twitter em função do período eleitoral.
 Comecemos pela parte mais fácil, um gráfico de frequências:
 
## Referências bibliográficas
